### ISSUE TITLE
Issue downloading Amnesia from GitHub (ch 13)

### ISSUE THREAD

**Issue by stratigos** [red-4/taking-off#11]
For chapter 13, when trying to use `Amnesia`, I get an error when downloading the package from Github. 

For this line of `deps()` : 

```elixir
[{:timex, "~> 2.1.4"}, {:amnesia, github: "meh/amnesia", tag: :master}] 
```
I get the following error:

```bash
* Updating amnesia (https://github.com/meh/amnesia.git)
** (ArgumentError) all arguments for System.cmd/3 must be binaries
    (elixir) lib/system.ex:613: System.cmd/3
    (mix) lib/mix/scm/git.ex:250: Mix.SCM.Git.git!/2
    (mix) lib/mix/scm/git.ex:124: Mix.SCM.Git.checkout/2
    (elixir) lib/file.ex:1419: File.cd!/2
    (mix) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
    (mix) lib/mix/dep/converger.ex:185: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:196: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:121: Mix.Dep.Converger.all/7
```

Although the video states not to download the package from Hex, I believe there has been updated version since the release of chapter 13. I am able to download the package fine with https://hex.pm/packages/amnesia/0.2.7, i.e., 

```elixir
{:amnesia, "~> 0.2.7"}
```

**Comment by WadeGulbrandsen** [comment]
Looks like something changed in mix since this course was made. You can no longer us an atom to specify the tag. You need to use a string. I changed it to the following and it worked.

`[{:timex, "~> 2.1.4"}, {:amnesia, github: "meh/amnesia", tag: "master"}]`

**Comment by robconery** [comment]
Thanks Wade - for what it's worth the default is `master` so you can leave the tag off if you want.
