### ISSUE TITLE
Physics.Repo not started

### ISSUE THREAD

**Issue by an21p** [red-4/taking-off#5]
While going through the book I hit a roadblock on getting data back from the database. When I try to query something I get this error.

I am using the files from the BOMBS AWAY Commit and just adding a planet schema file and editing the following planet.ex file
[planet.ex.txt](https://github.com/bigmachine-io/taking-off/files/852092/planet.ex.txt)

```
== Compilation error on file lib/physics/rocketry.ex ==
** (ArgumentError) repo Physics.Repo is not started, please ensure it is part of your supervision tree
    lib/ecto/query/planner.ex:65: Ecto.Query.Planner.query_lookup/5
    lib/ecto/query/planner.ex:48: Ecto.Query.Planner.query_with_cache/6
    lib/ecto/repo/queryable.ex:119: Ecto.Repo.Queryable.execute/5
    lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
    lib/planet.ex:21: Planet.select/0
    lib/physics/rocketry.ex:9: (module)
```

**Comment by robconery** [comment]
Did you figure it out? It's an Ecto error so hopefully you saw what to do...
