### ISSUE TITLE
Additional error in compiler_problem_test.exs (@ Chapter 8)

### ISSUE THREAD

**Issue by thegaryroberts** [red-4/taking-off#6]
in commit d2eb25f there is an error over and above the intentional errors discussed in the video. 

There are 2 methods named as "test rounding an integer". As such the test resolution process does not follow the same flow as the video or the book. Instead a "ExUnit.DuplicateTestError" is thrown and no test assertions are shown (failing or otherwise).

**Comment by thegaryroberts** [comment]
Ok moving further along the video (couldn't tell from the book as no function name is mentioned) I see this was *somewhat* intentional. *However* it did not result in just a warning with all the other tests being run. It resulted in the ExUnit exception noted above and no tests being run (in my case anyway). So it makes it difficult to follow along with the video/book. Have to jump about the chapter.

**Comment by robconery** [comment]
At the time I made the book/video ExUnit didn't throw with duplicate tests and it was easy to not notice that the name of the test was the differentiator. This isn't obvious, which is why I did it this way. Looks like ExUnit now throws, which is good.
