### ISSUE TITLE
Mnesia chapter issues

### ISSUE THREAD

**Issue by thegaryroberts** [red-4/taking-off#7]
I had 2 issues with amnesia_test.exs when completing this chapter:

1. Should be "Amnesia.start" instead of "Amnesia.Start"
- this only applies to the code shown in the video
- book & github code are correct

2. I needed to add a directive for "use Amnesia" in amnesia_test.exs  or i get
"(UndefinedFunctionError) function Amnesia.Helper.result/1 is undefined or private"
- seems to be missing from video, book & github code.
- think this is caused by a change to the Amnesia library (in Aug 2016).

**Comment by robconery** [comment]
Yep - thanks just updated the video. Appreciate it!

**Comment by robconery** [comment]
Oh - also you'll get an email RE when you can download the changes.
