### ISSUE TITLE
Concurrency Example Postgrex.close/1

### ISSUE THREAD

**Issue by thegaryroberts** [red-4/taking-off#8]
I get error Postgrex.close/1 is undefined or private in the example where we are using the Postgrex driver directly. The Postgrex docs only show close/3 & close!/3 (although 1 of the parameters is optional so I think that also makes it close/2).

**Comment by thegaryroberts** [comment]
I see now the Postgrex.close(pid) line is only in the video & the book. It's removed from the files here on github, along with the "res" return value.

**Comment by robconery** [comment]
Cheers thanks for this. I'm updating the videos/book currently and I'll make sure that gets fixed.

**Comment by robconery** [comment]
Good stuff - comment added thank you!
